# Generated by Django 2.2.4 on 2020-09-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20200917_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='state',
            new_name='condidtion',
        ),
        migrations.AddField(
            model_name='car',
            name='use_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
