# Generated by Django 2.2.4 on 2020-09-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20200917_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
