# Generated by Django 2.2.4 on 2020-09-17 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0004_car_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='condidtion',
            new_name='condition',
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('model_year', models.TextField(blank=True, null=True)),
                ('transmission', models.TextField(blank=True, null=True)),
                ('fuel_type', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('condidtion', models.TextField(blank=True, null=True)),
                ('use_state', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
