# Generated by Django 2.2.4 on 2020-09-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_auto_20200917_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ManyToManyField(to='APP.Images'),
        ),
    ]
