# Generated by Django 2.2.4 on 2020-09-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_auto_20200917_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='condidtion',
            new_name='condition',
        ),
    ]
