# Generated by Django 2.2.4 on 2020-09-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20200917_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='phone',
        ),
    ]
