# Generated by Django 2.2.4 on 2020-09-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_auto_20200917_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='creator',
        ),
    ]
