# Generated by Django 2.2.4 on 2020-09-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_auto_20200917_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
