# Generated by Django 2.2.4 on 2020-09-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Accountant', 'Accountant'), ('Liberian', 'Liberian')], default='dealer', max_length=100),
            preserve_default=False,
        ),
    ]
