# Generated by Django 2.2.4 on 2020-09-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_auto_20200919_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('summmary', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('author_description', models.TextField(blank=True, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
