# Generated by Django 2.2.4 on 2020-09-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_body',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
