# Generated by Django 2.2.4 on 2020-09-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_auto_20200920_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
