# Generated by Django 2.2.4 on 2020-09-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_article_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
