# Generated by Django 2.2.4 on 2020-09-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
