# Generated by Django 2.2.4 on 2020-09-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0020_userprofile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
