# Generated by Django 2.2.4 on 2020-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0023_car_feature_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
