# Generated by Django 2.2.4 on 2020-09-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0027_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
